import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class QuestionService {

  constructor() { }

ansver: any[]=[{id1:"i1",id2:"i2", q:"Sizning qanday avzallligingiz bor?", a:"men o`ziga ishongan, qobiliatli va faqat kelajakni o`ylab msuliatbilan harakat wiluvchi insonman lorejrkjfs sjfhskjfh  men hkksjkf wjin ketyotkan edim bit indson hciwi[wolib nenhahhfshhsjf"},{id1:"i1",id2:"i2",q:"Sizning ismingiz nega bunchalar chiroyliy?", a:"men o`ziga ishongan, qobiliatli va faqat kelajakni o`ylab msuliatbilan harakat wiluvchi insonman lorejrkjfs sjfhskjfh  men hkksjkf wjin ketyotkan edim bit indson hciwi[wolib nenhahhfshhsjf"},{id1:"i1",id2:"i2",q:"Sizning qanday avzallligingiz bor?", a:"men o`ziga ishongan, qobiliatli va faqat kelajakni o`ylab msuliatbilan harakat wiluvchi insonman lorejrkjfs sjfhskjfh  men hkksjkf wjin ketyotkan edim bit indson hciwi[wolib nenhahhfshhsjf"},{id1:"i1",id2:"i2",q:"Sizning qanday avzallligingiz bor?", a:"men o`ziga ishongan, qobiliatli va faqat kelajakni o`ylab msuliatbilan harakat wiluvchi insonman lorejrkjfs sjfhskjfh  men hkksjkf wjin ketyotkan edim bit indson hciwi[wolib nenhahhfshhsjf"},{id1:"i1",id2:"i2",q:"Sizning qanday avzallligingiz bor?", a:"men o`ziga ishongan, qobiliatli va faqat kelajakni o`ylab msuliatbilan harakat wiluvchi insonman lorejrkjfs sjfhskjfh  men hkksjkf wjin ketyotkan edim bit indson hciwi[wolib nenhahhfshhsjf"},{id1:"i1",id2:"i2",q:"Sizning qanday avzallligingiz bor?", a:"men o`ziga ishongan, qobiliatli va faqat kelajakni o`ylab msuliatbilan harakat wiluvchi insonman lorejrkjfs sjfhskjfh  men hkksjkf wjin ketyotkan edim bit indson hciwi[wolib nenhahhfshhsjf"},{id1:"i1",id2:"i2",q:"Sizning qanday avzallligingiz bor?", a:"men o`ziga ishongan, qobiliatli va faqat kelajakni o`ylab msuliatbilan harakat wiluvchi insonman lorejrkjfs sjfhskjfh  men hkksjkf wjin ketyotkan edim bit indson hciwi[wolib nenhahhfshhsjf"},{id1:"i1",id2:"i2",q:"Sizning qanday avzallligingiz bor?", a:"men o`ziga ishongan, qobiliatli va faqat kelajakni o`ylab msuliatbilan harakat wiluvchi insonman lorejrkjfs sjfhskjfh  men hkksjkf wjin ketyotkan edim bit indson hciwi[wolib nenhahhfshhsjf"},{id1:"i1",id2:"i2",q:"Sizning qanday avzallligingiz bor?", a:"men o`ziga ishongan, qobiliatli va faqat kelajakni o`ylab msuliatbilan harakat wiluvchi insonman lorejrkjfs sjfhskjfh  men hkksjkf wjin ketyotkan edim bit indson hciwi[wolib nenhahhfshhsjf"},{id1:"i1",id2:"i2",q:"Sizning qanday avzallligingiz bor?", a:"men o`ziga ishongan, qobiliatli va faqat kelajakni o`ylab msuliatbilan harakat wiluvchi insonman lorejrkjfs sjfhskjfh  men hkksjkf wjin ketyotkan edim bit indson hciwi[wolib nenhahhfshhsjf"}]

}
